name: Metrics
on:
  schedule:
    - cron: '45 23 * * *'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Update base
        uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: docs
          committer_message: "Update base metrics"
          template: repository
          user: The-FireHub-Project
          repo: the-firehub-project.github.io
          filename: resources/graphics/images/metrics/base.svg
          token: ${{ secrets.GH_TOKEN }}
          base_indepth: yes
      - name: Update pagespeed
        uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: docs
          committer_message: "Update pagespeed metrics"
          template: repository
          user: The-FireHub-Project
          repo: the-firehub-project.github.io
          filename: resources/graphics/images/metrics/pagespeed.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://the-firehub-project.github.io/
          plugin_pagespeed_detailed: yes
      - name: Update contributors
        uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: docs
          committer_message: "Update contributors metrics"
          template: repository
          user: The-FireHub-Project
          repo: the-firehub-project.github.io
          filename: resources/graphics/images/metrics/contributors.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_contributors: yes
          plugin_contributors_head: ${{ github.head_ref || github.ref_name }}
          plugin_contributors_contributions: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
              "🎈 Dot files":[".**"],
              "💢 Documentation":["README.md", "**/README.md"],
              "🥢 Others": ["*"]
            }
      - name: Update languages
        uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: docs
          committer_message: "Update languages metrics"
          template: repository
          user: The-FireHub-Project
          repo: the-firehub-project.github.io
          filename: resources/graphics/images/metrics/languages.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: true
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_recent_categories: data, markup, programming, prose
      - name: Update people
        uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: docs
          committer_message: "Update people metrics"
          template: repository
          user: The-FireHub-Project
          repo: the-firehub-project.github.io
          filename: resources/graphics/images/metrics/people.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: sponsors, contributors, stargazers, watchers, thanks
          #plugin_people_thanks: